ci(health)[OK-310] Add MongoDB health check to docker CI pipeline (#191)

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -77,5 +77,12 @@ jobs:
             exit 1
           fi
 
+      - name: Run health check on MongoDB
+        run: |
+          if ! docker exec obelisk_mongodb_container mongosh --username admin --password password --authenticationDatabase admin --eval "db.runCommand({ ping: 1 })" | grep -q 'ok: 1'; then
+            echo "MongoDB health check failed."
+            exit 1
+          fi
+
       - name: Stop docker containers
         run: docker compose down --volumes
